---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sat-deploy-to-cluster-group
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: continuous-delivery-context-secret
      description: name of the configmap containing the continuous delivery pipeline context secrets
      default: secure-properties
    - name: kubernetes-service-apikey-secret-key
      description: field in the secret that contains the api key used to login to ibmcloud kubernetes service
      default: apikey
    - name: satellite-cluster-group
      description: The name of the satellite cluster group
      default: ""
    - name: satellite-config
      description: The name of the satellite configuration deployed
      default: ""
    - name: satellite-config-version
      description: The name of the version of the satellite configuration deployed
      default: ""
    - name: satellite-subscription
      description: The name of the subscription of satellite configuration deployed
      default: ""
    - name: image-url
      description: URL of an image that is relevant to the deployment action
      default: ""
    - name: shuttle-properties-file
      description: name of the properties file that contain properties to include in the environment for the `cf-commands` snippet/script execution
      default: ""
    - name: setup-script
      description: script that typically set up environment before the _deployment_ script execution.
      default: ""
    - name: script
      description: _deployment_ script to be executed
      default: ""
    - name: post-execution-script
      description: script that get executed after the _deployment_ script has been executed.
      default: ""
    - name: pipeline-debug
      description: Pipeline debug mode. Value can be 0 or 1. Default to 0
      default: "0"
  results:
    - name: app-url
      description: The running application's URL (obtained from APP_URL variable set by the executed script)
    - name: satellite-config
      description: The name of the satellite configuration deployed
    - name: satellite-config-version
      description: The name of the version of the satellite configuration deployed
    - name: satellite-subscription
      description: The name of the subscription of satellite configuration deployed
  workspaces:
    - name: artifacts
      description: A workspace
      mountPath: /artifacts
  steps:
    - name: execute
      image: ibmcom/pipeline-base-image:2.12
      workingDir: /artifacts
      env:
        - name: BUILD_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/build-number']
        - name: PIPELINE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-id']
        - name: PIPELINE_STAGE_EXECUTION_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/tekton-pipeline']
        - name: PIPELINE_TRIGGERING_USER
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/triggered-by']
        - name: PIPELINE_BLUEMIX_API_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: $(params.kubernetes-service-apikey-secret-key)
        - name: SATELLITE_CLUSTER_GROUP
          value: $(params.satellite-cluster-group)
        - name: CONFIG_NAME
          value: $(params.satellite-config)
        - name: SUBSCRIPTION_NAME
          value: $(params.satellite-subscription)
        - name: VERSION_NAME
          value: $(params.satellite-config-version)
        - name: PIPELINE_IMAGE_URL
          value: $(params.image-url)
        - name: SHUTTLE_PROPERTIES_FILE
          value: $(params.shuttle-properties-file)
        - name: PIPELINE_DEBUG
          value: $(params.pipeline-debug)
      script: |
        #!/bin/bash
        set -e -o pipefail

        if [ $PIPELINE_DEBUG == 1 ]; then
            env
            pwd
            ls -l
            echo "=== cat /artifacts/_toolchain.json ==="
            cat /artifacts/_toolchain.json
            echo ""
            echo "======================================"
            trap env EXIT
            set -x
        fi

        # SETUP BEGIN
        ibmcloud config --check-version false
        export IBM_CLOUD_REGION=$(jq -r '.region_id' /artifacts/_toolchain.json | awk -F: '{print $3}')
        ibmcloud login -a $(params.ibmcloud-api) -r $IBM_CLOUD_REGION --apikey $PIPELINE_BLUEMIX_API_KEY
        export PIPELINE_TOOLCHAIN_ID=$(jq -r '.toolchain_guid' /artifacts/_toolchain.json)

        if [ "$SHUTTLE_PROPERTIES_FILE" ]; then
          source $SHUTTLE_PROPERTIES_FILE
          export $(cut -d= -f1 $SHUTTLE_PROPERTIES_FILE)
        fi

        # DO THE WORK
        $(params.script)

        # Record task results
        echo -n "$APP_URL" > $(results.app-url.path)
        echo -n "$CONFIG_NAME" > $(results.satellite-config.path)
        echo -n "$SUBSCRIPTION_NAME" > $(results.satellite-subscription.path)
        echo -n "$VERSION_NAME" > $(results.satellite-config-version.path)
      volumeMounts:
        - mountPath: /cd-config
          name: cd-config-volume
        - mountPath: /steps
          name: steps-volume
        - mountPath: /artifacts/_toolchain.json
          subPath: toolchain.json
          name: cd-config-volume
  volumes:
    - name: steps-volume
      emptyDir: {}
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json